#!/usr/bin/env bash
# install nginx web server & redirect
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "30i location /xwz {\nreturn 404 \"Ceci n'est pas une page\n\n\";\n}\n" /etc/nginx/sites-available/default
service nginx restart
