#!/usr/bin/env bash
# debug a web server on a docker container 
sudo apt-get update
sudo apt-get install nginx
sudo ln -sf /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
sudo service nginx restart
