#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
school="Best School"
i="1"
while ((i <= 10))
do
echo "$school" & i=$((i+1))
if ((i == 9))
then
    echo "Hi" & i=$((i+1))
fi
 done