#!/usr/bin/env bash
#ICP THEN UDP

current_host="127.0.0.1 localhost"
current_fb="157.240.11.35 facebook.com"
localhost_pair="127.0.0.2 localhost"
facebook_pair="8.8.8.8 facebook.com"
host=/etc/hosts
new_host=~/hosts.new
cp $host $new_host
sudo sed -i -e "/$current_host/ s/$localhost_pair/" $new_host
sudo sed -i -e "/$current_fb/ s/$facebook_pair/" $new_host
cp -f $new_host $host